# Generated by Django 2.0.7 on 2018-09-02 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(choices=[('甲醛的危害', '甲醛的危害'), ('除甲醛百科', '除甲醛百科'), ('除甲醛产品', '除甲醛产品'), ('除甲醛公司', '除甲醛公司'), ('除甲醛加盟', '除甲醛加盟'), ('除甲醛案例', '除甲醛案例')], default='除甲醛百科', max_length=20, unique=True, verbose_name='商品类别')),
                ('is_goods', models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否货源')),
                ('sequence', models.IntegerField(help_text='数字从小到大排列分类位置.', unique=True, verbose_name='排序')),
                ('head_title', models.TextField(verbose_name='HeadTitle')),
                ('head_desc', models.TextField(verbose_name='HeadDesc')),
                ('head_keywords', models.TextField(verbose_name='HeadKeywords')),
            ],
            options={
                'verbose_name': '产品类别',
                'db_table': 'dashboard_category',
                'verbose_name_plural': '产品类别',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=15, verbose_name='站点')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('sequence', models.IntegerField(help_text='数字从小到大排列标签位置.', unique=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '友情链接',
                'db_table': 'dashboard_links',
                'verbose_name_plural': '友情链接',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='', max_length=100, verbose_name='网站名称')),
                ('head_title', models.TextField(default='', max_length=1000, verbose_name='首页标题')),
                ('head_desc', models.TextField(default='', max_length=1000, verbose_name='首页描述')),
                ('head_keywords', models.TextField(default='', max_length=1000, verbose_name='首页关键字')),
                ('article_sub_length', models.IntegerField(default=300, verbose_name='文章摘要长度')),
                ('sidebar_flow_info_count', models.IntegerField(default=10, verbose_name='侧边栏信息流数目')),
                ('sidebar_recomm_count', models.IntegerField(default=5, verbose_name='侧边栏推荐帖文数目')),
                ('qq_bar_code', models.ImageField(upload_to='site/qq', verbose_name='QQ二维码')),
                ('qq', models.CharField(max_length=20, verbose_name='QQ')),
                ('wechat_pay_code', models.ImageField(upload_to='site/wechat', verbose_name='微信支付维码')),
                ('alipay_code', models.ImageField(upload_to='site/alipay', verbose_name='支付宝二维码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('beiancode', models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='备案号')),
                ('analyticscode', models.TextField(default='', max_length=1000, verbose_name='网站统计代码')),
                ('show_gongan_code', models.BooleanField(default=False, verbose_name='是否显示公安备案号')),
                ('gongan_beiancode', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='公安备案号')),
            ],
            options={
                'verbose_name': '网站配置',
                'db_table': 'dashboard_settings',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名')),
                ('head_title', models.TextField(verbose_name='HeadTitle')),
                ('head_desc', models.TextField(verbose_name='HeadDesc')),
                ('head_keywords', models.TextField(verbose_name='HeadKeywords')),
            ],
            options={
                'verbose_name': '标签',
                'db_table': 'dashboard_tag',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
    ]
