# Generated by Django 2.0.7 on 2018-09-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_goods',
        ),
    ]
